// script.js
document.addEventListener('DOMContentLoaded', function() {
  const animalBreeds = [
    'Lion', 'Tiger', 'Bear', 'Elephant', 'Giraffe', // Add more breeds
    // Up to 300 breeds
  ];

  const zooMap = document.getElementById('zoo-map');

  animalBreeds.forEach((breed, index) => {
    const enclosure = document.createElement('div');
    enclosure.className = 'enclosure';
    enclosure.id = `enclosure-${index + 1}`;

    const heading = document.createElement('h3');
    heading.textContent = breed + ' Enclosure';
    enclosure.appendChild(heading);

    const animalsDiv = document.createElement('div');
    animalsDiv.className = 'animals';

    for (let i = 1; i <= 4; i++) {
      const animalDiv = document.createElement('div');
      animalDiv.className = 'animal';
      animalDiv.textContent = `${breed} ${i}`;
      animalsDiv.appendChild(animalDiv);
    }

    enclosure.appendChild(animalsDiv);
    zooMap.appendChild(enclosure);
  });
});